name: Publish to Github Pages

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo gem install sass
          sudo gem install compass
          npm install

      - name: Build package
        run: |
          grunt dev

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
